### PR TITLE
tamrin emtiazi

### PR DESCRIPTION
**Pull request by bloody-dante**
I don't know how to add my name to my sending files but my name is Amirhossein Vosoughi

### CODE REVIEW

**Comment by parsa-abbasi** [comment]
You are submitting two folders (www.zoomit.ir and zoomit.ir). Please remove the www.zoomit.ir folder.

**Comment by parsa-abbasi** [comment]
Furthermore, add a README.md file to the folder and write a brief description of your project please.

**Comment by bloody-dante** [comment]
[README.md](https://github.com/QueraTeam/dataanalysis_bootcamp_crawler/files/10678185/README.md)

**Comment by bloody-dante** [comment]
Thanks for notifying me about the defects in my pull requests. now I delete one file and added a readme.md file so I hope its compelete now

**Pull request merged**
